# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
notice = "deny"
git-fetch-with-cli = true
ignore = [
]

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true
build.executables = "deny"
build.interpreted = "deny"
build.include-dependencies = true
build.include-workspace = false # covered by tools/tidy.sh
build.include-archives = true
build.allow-build-scripts = [
    { name = "proc-macro2" }, # via serde_derive
    { name = "serde" },
    { name = "windows_aarch64_gnullvm" }, # via home
    { name = "windows_aarch64_msvc" }, # via home
    { name = "windows_i686_gnu" }, # via home
    { name = "windows_i686_gnullvm" }, # via home
    { name = "windows_i686_msvc" }, # via home
    { name = "windows_x86_64_gnu" }, # via home
    { name = "windows_x86_64_gnullvm" }, # via home
    { name = "windows_x86_64_msvc" }, # via home
]
build.bypass = [
    # Import libraries are necessary because raw-dylib (requires 1.71+ for x86, 1.65+ for others) is not available on MSRV of them.
    { name = "windows_aarch64_gnullvm", allow-globs = ["lib/*.a"] }, # via home
    { name = "windows_aarch64_msvc", allow-globs = ["lib/*.lib"] }, # via home
    { name = "windows_i686_gnu", allow-globs = ["lib/*.a"] }, # via home
    { name = "windows_i686_gnullvm", allow-globs = ["lib/*.a"] }, # via home
    { name = "windows_i686_msvc", allow-globs = ["lib/*.lib"] }, # via home
    { name = "windows_x86_64_gnu", allow-globs = ["lib/*.a"] }, # via home
    { name = "windows_x86_64_gnullvm", allow-globs = ["lib/*.a"] }, # via home
    { name = "windows_x86_64_msvc", allow-globs = ["lib/*.lib"] }, # via home
]

# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
version = 2
unused-allowed-license = "deny"
private.ignore = true
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016", # unicode-ident
]

# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
]
